AwesomeTODOList/Models/TODOItem.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AwesomeTODOList.Models
{
    public class TODOItem
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        public string Title { get; set; }
        public string Description { get; set; }

        [Required]
        [Display(Name = "Due date")]
        public DateTime DueDate { get; set; }
        public bool IsCompleted { get; set; }
    }
}

AwesomeTODOList/Models/TODOList.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AwesomeTODOList.Models
{
    public static class TODOList
    {
        public static List<TODOItem> Items { get; set; }

        static TODOList()
        {
            Items = new List<TODOItem>();
            Items.Add(new TODOItem
            {
                Title = "Task 1",
                Description = "Task 1 Description",
                DueDate = new DateTime(2019, 6, 30),
                IsCompleted = false
            });
            Items.Add(new TODOItem
            {
                Title = "Task 2",
                Description = "Task 2 Description",
                DueDate = new DateTime(2019, 7, 10),
                IsCompleted = true
            });
        }
    }
}

AwesomeTODOList/Controllers/TODOController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AwesomeTODOList.Managers;
using AwesomeTODOList.Models;

namespace AwesomeTODOList.Controllers
{
    public class TODOController : Controller
    {
        private TODOItemManager _dbManager = new TODOItemManager();

        // GET: TODO
        public ActionResult GetAllTasks()
        {
            var items = _dbManager.GetAllTasks();
            return View(items);
        }

        public ActionResult GetCompleted(bool completed)
        {
            //List<TODOItem> items = new List<TODOItem>();

            //foreach (var item in TODOList.Items)
            //{
            //    if(item.IsCompleted == completed)
            //    {
            //        items.Add(item);
            //    }
            //}

            var items = TODOList.Items.Where(i => i.IsCompleted == completed).ToList();

            return View("GetAllTasks", items);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(TODOItem todo)
        {
            if(!ModelState.IsValid)
            {
                return View(todo);
            }

            _dbManager.Insert(todo);

            TempData["Message"] = "Task created!";
            return RedirectToAction("GetAllTasks");
        }
        
        public ActionResult Edit(int id)
        {
            var todo = _dbManager.GetItemById(id);
            return View(todo);
        }
        
        [HttpPost]
        public ActionResult Edit(TODOItem todo)
        {
            if(!ModelState.IsValid)
            {
                return View(todo);
            }

            // Update database
            _dbManager.Update(todo);

            return RedirectToAction("GetAllTasks");
        }
    }
}

AwesomeTODOList/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="@Url.Content("~/www/favicon.ico")">

    <title>Dashboard Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="@Url.Content("~/www/dist/css/bootstrap.min.css")" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="@Url.Content("~/www/dashboard.css")" rel="stylesheet">
</head>

<body>
    <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Awesome Task List</a>
        <ul class="navbar-nav px-3">
            <li class="nav-item text-nowrap">
                <a class="nav-link" href="#">Login</a>
            </li>
        </ul>
    </nav>

    <div class="container-fluid">
        <div class="row">
            <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                <div class="sidebar-sticky">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link active" href="#">
                                All Tasks
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                Incomplete Tasks
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                Completed Tasks
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>



            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
                @RenderBody()
            </main>
        </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="@Url.Content("~/www/assets/js/popper.min.js")"></script>
    <script src="@Url.Content("~/www/dist/js/bootstrap.min.js")"></script>
</body>
</html>

AwesomeTODOList/Views/TODO/Create.cshtml
@model AwesomeTODOList.Models.TODOItem
<h2>Create new task</h2>

@using (Html.BeginForm("Create", "TODO", FormMethod.Post))
{
    @Html.ValidationSummary()
    <div class="form-row">
        <div class="col-md-4 mb-3">
            @Html.LabelFor(i => i.Title)
            @*<label for="Title">Title</label>*@
            @Html.TextBoxFor(i => i.Title, new { @class = "form-control", placeholder = "Title" })
            @Html.ValidationMessageFor(i => i.Title)
            @*<input type="text" class="form-control" id="Title" name="Title" placeholder="Title">*@
        </div>
    </div>
    <div class="form-row">
        <div class="col-md-4 mb-3">
            @Html.LabelFor(i => i.Description)
            @*<label for="Description">Description</label>*@
            @Html.TextBoxFor(i => i.Description, new { @class = "form-control", placeholder = "Description" })
            @Html.ValidationMessageFor(i => i.Description)
            @*<input type="text" class="form-control" id="Description" name="Description" placeholder="Description">*@
        </div>
    </div>
    <div class="form-row">
        <div class="col-md-4 mb-3">
            @Html.LabelFor(i => i.DueDate)
            @*<label for="Title">Due date</label>*@
            @Html.TextBoxFor(i => i.DueDate, new { @class = "form-control", placeholder = "Due date" })
            @Html.ValidationMessageFor(i => i.DueDate)
            @*<input type="text" class="form-control" id="DueDate" name="DueDate" placeholder="Due date">*@
        </div>
    </div>

    <button class="btn btn-primary" type="submit">Create</button>
    <button type="button" class="btn btn-primary" onclick="window.location.href='@Url.Action("GetAllTasks", "TODO")'">Cancel</button>
}

@*<form method="post" action="@Url.Action("Create", "TODO")">
        <div class="form-row">
            <div class="col-md-4 mb-3">
                <label for="Title">Title</label>
                <input type="text" class="form-control" id="Title" name="Title" placeholder="Title">

            </div>
        </div>
        <div class="form-row">
            <div class="col-md-4 mb-3">
                <label for="Description">Description</label>
                <input type="text" class="form-control" id="Description" name="Description" placeholder="Description">
            </div>
        </div>
        <div class="form-row">
            <div class="col-md-4 mb-3">
                <label for="Title">Due date</label>
                <input type="text" class="form-control" id="DueDate" name="DueDate" placeholder="Due date">
            </div>
        </div>

        <button class="btn btn-primary" type="submit">Create</button>
        <button type="button" class="btn btn-primary" onclick="window.location.href='@Url.Action("GetAllTasks", "TODO")'">Cancel</button>
    </form>*@

AwesomeTODOList/Views/TODO/GetAllTasks.cshtml
@model IEnumerable<AwesomeTODOList.Models.TODOItem>

<p>@TempData["Message"]</p>
<h2>All tasks</h2>
<div class="table-responsive">
    <table class="table table-striped table-sm">
        <thead>
            <tr>
                <th colspan="5">
                    <a href="@Url.Action("Create", "TODO")">Create task</a>
                </th>
            </tr>
            <tr>
                <th>Title</th>
                <th>Description</th>
                <th>Due date</th>
                <th>Completed</th>
                <td>Actions</td>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {

                string cssClass;

                if (item.IsCompleted)
                {
                    cssClass = "table-success";
                }
                else
                {
                    cssClass = "table-active";
                }
                <tr class="@cssClass">
                    <td>@item.Title</td>
                    <td>@item.Description</td>
                    <td>@item.DueDate</td>
                    <td>@item.IsCompleted</td>
                    <td>
                        <a href="@Url.Action("Edit", "TODO", new { id = item.Id})">Edit</a> |
                        <a href="#">Delete</a> |
                        <a href="#">Complete</a>
                    </td>
                </tr>
            }
            @*<tr class="table-active">
                    <td>Wash the car.</td>
                    <td></td>
                    <td>25/11/2018 12:00:00 πμ</td>
                    <td>False</td>
                    <td>
                        <a href="#">Edit</a> |
                        <a href="#">Delete</a> |
                        <a href="#">Complete</a>
                    </td>
                </tr>
                <tr class="table-success">
                    <td>Prepare MVC exercise - example.</td>
                    <td></td>
                    <td></td>
                    <td>True</td>
                    <td>
                        <a href="#">Edit</a> |
                        <a href="#">Delete</a> |
                        <a href="#">Complete</a>
                    </td>
                </tr>*@
            <!-- On rows -->
            <!-- On cells (`td` or `th`) -->

        </tbody>
    </table>
</div>

AwesomeTODOList/Views/TODO/GetCompleted.cshtml
@model List<AwesomeTODOList.Models.TODOItem>
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="@Url.Content("~/www/favicon.ico")">

    <title>Dashboard Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="@Url.Content("~/www/dist/css/bootstrap.min.css")" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="@Url.Content("~/www/dashboard.css")" rel="stylesheet">
</head>

<body>
    <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Awesome Task List</a>
        <ul class="navbar-nav px-3">
            <li class="nav-item text-nowrap">
                <a class="nav-link" href="#">Login</a>
            </li>
        </ul>
    </nav>

    <div class="container-fluid">
        <div class="row">
            <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                <div class="sidebar-sticky">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link active" href="#">
                                All Tasks
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                Incomplete Tasks
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                Completed Tasks
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>



            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
                <h2>All tasks</h2>
                <div class="table-responsive">
                    <table class="table table-striped table-sm">
                        <thead>
                            <tr>
                                <th colspan="5">
                                    <a href="/Dashboard/Create">Create task</a>
                                </th>
                            </tr>
                            <tr>
                                <th>Title</th>
                                <th>Description</th>
                                <th>Due date</th>
                                <th>Completed</th>
                                <td>Actions</td>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {

                                string cssClass;

                                if (item.IsCompleted)
                                {
                                    cssClass = "table-success";
                                }
                                else
                                {
                                    cssClass = "table-active";
                                }
                                <tr class="@cssClass">
                                    <td>@item.Title</td>
                                    <td>@item.Description</td>
                                    <td>@item.DueDate</td>
                                    <td>@item.IsCompleted</td>
                                    <td>
                                        <a href="#">Edit</a> |
                                        <a href="#">Delete</a> |
                                        <a href="#">Complete</a>
                                    </td>
                                </tr>
                            }
                            @*<tr class="table-active">
                                    <td>Wash the car.</td>
                                    <td></td>
                                    <td>25/11/2018 12:00:00 πμ</td>
                                    <td>False</td>
                                    <td>
                                        <a href="#">Edit</a> |
                                        <a href="#">Delete</a> |
                                        <a href="#">Complete</a>
                                    </td>
                                </tr>
                                <tr class="table-success">
                                    <td>Prepare MVC exercise - example.</td>
                                    <td></td>
                                    <td></td>
                                    <td>True</td>
                                    <td>
                                        <a href="#">Edit</a> |
                                        <a href="#">Delete</a> |
                                        <a href="#">Complete</a>
                                    </td>
                                </tr>*@
                            <!-- On rows -->
                            <!-- On cells (`td` or `th`) -->

                        </tbody>
                    </table>
                </div>
            </main>


        </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="@Url.Content("~/www/assets/js/popper.min.js")"></script>
    <script src="@Url.Content("~/www/dist/js/bootstrap.min.js")"></script>
</body>
</html>